name: 下载并合并TXT文件

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'  # 每天北京时间上午11点运行
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write

jobs:
  download-and-merge:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码库
      uses: actions/checkout@v2

    - name: 设置Python环境
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: 安装requests库
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: 运行下载和合并脚本
      run: python merge_txt.py

    - name: 提交并推送更改
      run: |
        git config --global user.name "zht298"
        git config --global user.email "zht19886@gmail.com"
        git pull origin main  # 先拉取远程更改
        git add merged_output.txt file1.txt file2.txt file3.txt file4.txt file5.txt file6.txt  # 添加所有需要跟踪的文件
        git commit -m "Add merged output TXT file"
        git push
