name: Download and Merge TXT Files

on:
  push:
    branches:
      - main
  schedule:
       - cron: '0 0 * * *' # 每天0点运行
  workflow_dispatch:   # 允许手动触发

jobs:
  download-and-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run download and merge script
      run: |
        python main.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add merged_output.txt
        git commit -m 'Add merged output TXT file'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
